---
title: "Extreme Value Theory Insight Code"
output: html_notebook
---

This notebook is for getting some initial insights of how to model the extreme values.

```{r}
# load libraries
library(SpatialExtremes)
library(ggplot2)
library(dplyr)
library(maps)
```
Print all avaiable dataset in SpatialExtreme package
```{r}
print("Available datasets in SpatialExtremes:")
data(package = "SpatialExtremes")

```
We use the dataset called "rainfall (rain)"
```{r}
print("Dataset structure:")
str(rain)


```
```{r}
print("\nDataset summary:")
summary(rain)
```
First few lines of the dataset
```{r}
print("\nFirst few rows:")
head(rain)

```
```{r}
# Check for missing values
print("\nMissing values:")
colSums(is.na(rain))
```
Visualise the spatial distribution of the stations

```{r}
plot(coord[, "lon"], coord[, "lat"], 
     main = "Spatial Distribution of Rainfall Stations",
     xlab = "Longitude", ylab = "Latitude",
     pch = 19, col = "blue", cex = 1.2)

```
fit the model
```{r}
fit <- fitmaxstab(data = rain, coord = coord[, 1:2], cov.mod = "brown")
```

print some summary info of this fitting
```{r}
summary(fit)

```
plot the fitting
```{r}
plot(fit, which = "variogram")

```



